image: docker:19.03.12
services:
  - docker:19.03.12-dind

variables:
  DOCKER_IMAGE_PATH: "sandrasoft/mvp-v2/his-api"
  DOCKER_IMAGE_NAME: "his-api:latest"

before_script:
  # Add git
  - apk update && apk add git
  # Login docker
  - docker login -u $CI_HIS_API_USER -p $CI_HIS_API_PASS registry.gitlab.com

build_his_api:
  stage: build
  script:
    - docker build -t tmp-image .
    - docker tag tmp-image registry.gitlab.com/$DOCKER_IMAGE_PATH/$DOCKER_IMAGE_NAME
    - docker push registry.gitlab.com/$DOCKER_IMAGE_PATH/$DOCKER_IMAGE_NAME