version: "3.5"

services:
  api-his:
    build: 
      context: ./
    ports:
      - 2001:80
    restart: always
    environment: 
      - HIS_APP_MSSQL_DB_HOST=db
      - HIS_APP_MSSQL_DB_NAME=ERP
      - HIS_APP_MSSQL_DB_USER=sa
      - HIS_APP_MSSQL_DB_PASSWORD=123
      - HIS_APP_ACCESS_TOKEN_ENCRYPTION_KEY=Encription#Key?Unique